import Head from "next/head";
import { Button } from "../components/Button/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-4xl font-bold  text-red-700">ヘッダー</h1>
        <Button
          outlined={false}
          size={"small"}
          onClick={() => (document.location.href = "https://reactjs.org")}
        >
          Submit
        </Button>
      </main>
    </>
  );
}
